/*-
 * WSDL stubs for:  http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl
 *   Generated by:  churchil
 *           Date:  Wed Dec 29 16:44:36 2004
 *        Emitter:  Objective-C
 */

#ifndef __NDFDStub__
#define __NDFDStub__

#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import "WSGeneratedObj.h"

/*-
 *   Web Service:  ndfdXML
 * Documentation:  The service input includes a latitude and longitude pair, plus the
 *                 product type.  You can also provide 
 *                                      an optional start and end time representing
 *                 the period of time that you want data for.  For the 
 *                                      time-series product you need to provide a list
 *                 of boolean values corresponding to which 
 *                                      weather values should appear in the time
 *                 series product.
 */
/*-
 *   Method Name:  NDFDgenByDay
 * Documentation:  Returns National Weather Service digital weather forecast data
 *                 summarized over either 24- or 12-hourly periods
 */

@interface NDFDgenByDay : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(double) in_latitude in_longitude:(double) in_longitude in_startDate:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|date */) in_startDate in_numDays:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_numDays in_format:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|formatType */) in_format;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* NDFDgenByDay */


/*-
 *   Method Name:  NDFDgen
 * Documentation:  Returns National Weather Service digital weather forecast data
 */

@interface NDFDgen : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(double) in_latitude in_longitude:(double) in_longitude in_product:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|productType */) in_product in_startTime:(NSDate*) in_startTime in_endTime:(NSDate*) in_endTime in_weatherParameters:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|weatherParametersType */) in_weatherParameters;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* NDFDgen */


/*-
 * Web Service:  ndfdXML
 */
@interface ndfdXMLService : NSObject 

+ (id) NDFDgenByDay:(double) in_latitude in_longitude:(double) in_longitude in_startDate:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|date */) in_startDate in_numDays:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_numDays in_format:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|formatType */) in_format;
+ (id) NDFDgen:(double) in_latitude in_longitude:(double) in_longitude in_product:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|productType */) in_product in_startTime:(NSDate*) in_startTime in_endTime:(NSDate*) in_endTime in_weatherParameters:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|weatherParametersType */) in_weatherParameters;

@end;


#endif /* __NDFDStub__ */
/*-
 * End of WSDL document at
 * http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl
 */
