/*-
 * WSDL stubs for:  http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl
 *   Generated by:  churchil
 *           Date:  Wed Dec 29 16:44:36 2004
 *        Emitter:  Objective-C
 */

#import "NDFDStub.h"

/*-
 *   Method Name:  NDFDgenByDay
 * Documentation:  Returns National Weather Service digital weather forecast data
 *                 summarized over either 24- or 12-hourly periods
 */
@implementation NDFDgenByDay
- (void) setParameters:(double) in_latitude in_longitude:(double) in_longitude in_startDate:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|date */) in_startDate in_numDays:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_numDays in_format:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|formatType */) in_format
{
    id _paramValues[] = {    
        [NSNumber numberWithDouble: in_latitude],        
        [NSNumber numberWithDouble: in_longitude],        
        in_startDate,        
        in_numDays,        
        in_format,        
    };    
    NSString* _paramNames[] = {    
        @"latitude",        
        @"longitude",        
        @"startDate",        
        @"numDays",        
        @"format",        
    };    
    [super setParameters:5 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"dwmlByDayOut"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://www.nws.noaa.gov/forecasts/xml/SOAP_server/ndfdXMLserver.php"            
                 methodName: @"NDFDgenByDay"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDay"            
            methodNamespace: @"http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl"            
        ];        
}

@end; /* NDFDgenByDay */


/*-
 *   Method Name:  NDFDgen
 * Documentation:  Returns National Weather Service digital weather forecast data
 */
@implementation NDFDgen
- (void) setParameters:(double) in_latitude in_longitude:(double) in_longitude in_product:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|productType */) in_product in_startTime:(NSDate*) in_startTime in_endTime:(NSDate*) in_endTime in_weatherParameters:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|weatherParametersType */) in_weatherParameters
{
    id _paramValues[] = {    
        [NSNumber numberWithDouble: in_latitude],        
        [NSNumber numberWithDouble: in_longitude],        
        in_product,        
        in_startTime,        
        in_endTime,        
        in_weatherParameters,        
    };    
    NSString* _paramNames[] = {    
        @"latitude",        
        @"longitude",        
        @"product",        
        @"startTime",        
        @"endTime",        
        @"weatherParameters",        
    };    
    [super setParameters:6 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"xmlOut"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://www.nws.noaa.gov/forecasts/xml/SOAP_server/ndfdXMLserver.php"            
                 methodName: @"NDFDgen"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgen"            
            methodNamespace: @"http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl"            
        ];        
}

@end; /* NDFDgen */



@implementation ndfdXMLService

+ (id) NDFDgenByDay:(double) in_latitude in_longitude:(double) in_longitude in_startDate:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|date */) in_startDate in_numDays:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_numDays in_format:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|formatType */) in_format
{
    id result = NULL;    
    NDFDgenByDay* _invocation = [[NDFDgenByDay alloc] init];    
    [_invocation setParameters: in_latitude in_longitude:in_longitude in_startDate:in_startDate in_numDays:in_numDays in_format:in_format];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) NDFDgen:(double) in_latitude in_longitude:(double) in_longitude in_product:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|productType */) in_product in_startTime:(NSDate*) in_startTime in_endTime:(NSDate*) in_endTime in_weatherParameters:(CFTypeRef /* Complex type http://www.nws.noaa.gov/forecasts/xml/DWMLgen/schema/ndfdXML.xsd|weatherParametersType */) in_weatherParameters
{
    id result = NULL;    
    NDFDgen* _invocation = [[NDFDgen alloc] init];    
    [_invocation setParameters: in_latitude in_longitude:in_longitude in_product:in_product in_startTime:in_startTime in_endTime:in_endTime in_weatherParameters:in_weatherParameters];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at
 * http://www.nws.noaa.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl
 */
