/*-
 * WSDL stubs for:  /Volumes/Lore/Desktop/googleapi/GoogleSearch.wsdl
 *   Generated by:  nicholas
 *           Date:  Sat Jan  1 08:20:31 2005
 *        Emitter:  Objective-C
 */

#ifndef __QSGoogleStub__
#define __QSGoogleStub__

#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import "WSGeneratedObj.h"

/*-
 *   Web Service:  GoogleSearchService
 * Documentation:  <not documented>
 */
/*-
 *   Method Name:  doSpellingSuggestion
 * Documentation:  <no documentation>
 */

@interface doSpellingSuggestion : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_key in_phrase:(NSString*) in_phrase;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* doSpellingSuggestion */


/*-
 *   Method Name:  doGoogleSearch
 * Documentation:  <no documentation>
 */

@interface doGoogleSearch : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_key in_q:(NSString*) in_q in_start:(SInt32) in_start in_maxResults:(SInt32) in_maxResults in_filter:(BOOL) in_filter in_restrict:(NSString*) in_restrict in_safeSearch:(BOOL) in_safeSearch in_lr:(NSString*) in_lr in_ie:(NSString*) in_ie in_oe:(NSString*) in_oe;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* doGoogleSearch */


/*-
 *   Method Name:  doGetCachedPage
 * Documentation:  <no documentation>
 */

@interface doGetCachedPage : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_key in_url:(NSString*) in_url;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* doGetCachedPage */


/*-
 * Web Service:  GoogleSearchService
 */
@interface GoogleSearchService : NSObject 

+ (id) doSpellingSuggestion:(NSString*) in_key in_phrase:(NSString*) in_phrase;
+ (id) doGoogleSearch:(NSString*) in_key in_q:(NSString*) in_q in_start:(SInt32) in_start in_maxResults:(SInt32) in_maxResults in_filter:(BOOL) in_filter in_restrict:(NSString*) in_restrict in_safeSearch:(BOOL) in_safeSearch in_lr:(NSString*) in_lr in_ie:(NSString*) in_ie in_oe:(NSString*) in_oe;
+ (id) doGetCachedPage:(NSString*) in_key in_url:(NSString*) in_url;

@end;


#endif /* __QSGoogleStub__ */
/*-
 * End of WSDL document at /Volumes/Lore/Desktop/googleapi/GoogleSearch.wsdl
 */
