/*-
 * WSDL stubs for:  /Volumes/Lore/Desktop/googleapi/GoogleSearch.wsdl
 *   Generated by:  nicholas
 *           Date:  Sat Jan  1 08:20:31 2005
 *        Emitter:  Objective-C
 */

#import "QSGoogleStub.h"

/*-
 *   Method Name:  doSpellingSuggestion
 * Documentation:  <no documentation>
 */
@implementation doSpellingSuggestion
- (void) setParameters:(NSString*) in_key in_phrase:(NSString*) in_phrase
{
    id _paramValues[] = {    
        in_key,        
        in_phrase,        
    };    
    NSString* _paramNames[] = {    
        @"key",        
        @"phrase",        
    };    
    [super setParameters:2 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://api.google.com/search/beta2"            
                 methodName: @"doSpellingSuggestion"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:GoogleSearchAction"            
            methodNamespace: @"urn:GoogleSearch"            
        ];        
}

@end; /* doSpellingSuggestion */


/*-
 *   Method Name:  doGoogleSearch
 * Documentation:  <no documentation>
 */
@implementation doGoogleSearch
- (void) setParameters:(NSString*) in_key in_q:(NSString*) in_q in_start:(SInt32) in_start in_maxResults:(SInt32) in_maxResults in_filter:(BOOL) in_filter in_restrict:(NSString*) in_restrict in_safeSearch:(BOOL) in_safeSearch in_lr:(NSString*) in_lr in_ie:(NSString*) in_ie in_oe:(NSString*) in_oe
{
    id _paramValues[] = {    
        in_key,        
        in_q,        
        [NSNumber numberWithInt: in_start],        
        [NSNumber numberWithInt: in_maxResults],        
        [NSNumber numberWithBool: in_filter],        
        in_restrict,        
        [NSNumber numberWithBool: in_safeSearch],        
        in_lr,        
        in_ie,        
        in_oe,        
    };    
    NSString* _paramNames[] = {    
        @"key",        
        @"q",        
        @"start",        
        @"maxResults",        
        @"filter",        
        @"restrict",        
        @"safeSearch",        
        @"lr",        
        @"ie",        
        @"oe",        
    };    
    [super setParameters:10 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://api.google.com/search/beta2"            
                 methodName: @"doGoogleSearch"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:GoogleSearchAction"            
            methodNamespace: @"urn:GoogleSearch"            
        ];        
}

@end; /* doGoogleSearch */


/*-
 *   Method Name:  doGetCachedPage
 * Documentation:  <no documentation>
 */
@implementation doGetCachedPage
- (void) setParameters:(NSString*) in_key in_url:(NSString*) in_url
{
    id _paramValues[] = {    
        in_key,        
        in_url,        
    };    
    NSString* _paramNames[] = {    
        @"key",        
        @"url",        
    };    
    [super setParameters:2 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://api.google.com/search/beta2"            
                 methodName: @"doGetCachedPage"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:GoogleSearchAction"            
            methodNamespace: @"urn:GoogleSearch"            
        ];        
}

@end; /* doGetCachedPage */



@implementation GoogleSearchService

+ (id) doSpellingSuggestion:(NSString*) in_key in_phrase:(NSString*) in_phrase
{
    id result = NULL;    
    doSpellingSuggestion* _invocation = [[doSpellingSuggestion alloc] init];    
    [_invocation setParameters: in_key in_phrase:in_phrase];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) doGoogleSearch:(NSString*) in_key in_q:(NSString*) in_q in_start:(SInt32) in_start in_maxResults:(SInt32) in_maxResults in_filter:(BOOL) in_filter in_restrict:(NSString*) in_restrict in_safeSearch:(BOOL) in_safeSearch in_lr:(NSString*) in_lr in_ie:(NSString*) in_ie in_oe:(NSString*) in_oe
{
    id result = NULL;    
    doGoogleSearch* _invocation = [[doGoogleSearch alloc] init];    
    [_invocation setParameters: in_key in_q:in_q in_start:in_start in_maxResults:in_maxResults in_filter:in_filter in_restrict:in_restrict in_safeSearch:in_safeSearch in_lr:in_lr in_ie:in_ie in_oe:in_oe];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) doGetCachedPage:(NSString*) in_key in_url:(NSString*) in_url
{
    id result = NULL;    
    doGetCachedPage* _invocation = [[doGetCachedPage alloc] init];    
    [_invocation setParameters: in_key in_url:in_url];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at /Volumes/Lore/Desktop/googleapi/GoogleSearch.wsdl
 */
